### ISSUE TITLE
Change PostgresSQL Driver: psycopg2 -> pg8000

### ISSUE THREAD

**Issue by cr0hn** [BBVA/deeptracy#56]
Currently the Postgres driver for Alchemy is psycopg2 (LGPL). Their license is incompatible with deeptracy acceptance terms.

Change **psycopg2** -> **pg8000** (BSD)

Change needed in the connection string: 

postgresql+**psycopg2**://user:password@host:port/dbname

To

postgresql+**pg8000**://user:password@host:port/dbname

**Comment by Sergiodfdez** [comment]
License approved
