### ISSUE TITLE
error: version_part = pattern.split(parts[1])[1] 

### ISSUE THREAD

**Issue by angelbarrera92** [BBVA/deeptracy#92]
Good morning. Good morning. 
First of all thank you very much for this project. It was absolutely necessary. 
I'm having some trouble getting into deeptracy + patton. 

First I followed patton's step-by-step instructions: [`https://patton-server.readthedocs.io/en/latest/quickstart.html#first-of-run-patton-server`](https://patton-server.readthedocs.io/en/latest/quickstart.html#first-of-run-patton-server).
This one looks like it's raised well. 

Then I tried to start the deeptracy service [`https://deeptracy.readthedocs.io/en/latest/installation.html#bringing-up-the-environment`](https://deeptracy.readthedocs.io/en/latest/installation.html#bringing-up-the-environment). When I create a project and a scan, the scan fails. 

I did this requests:
```bash
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"repo":"https://github.com/BBVA/deeptracy-api.git","name":"deeptracy-api-test"}' \
  http://localhost:80/api/1/project/

curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"project_id":"54ef977d835c48459ba85c2e9e82931f","lang":"python"}' \
  http://localhost:80/api/1/scan/
```
And the log output is....

```bash
deeptracy_1      | Traceback (most recent call last):
deeptracy_1      |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
deeptracy_1      |     R = retval = fun(*args, **kwargs)
deeptracy_1      |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
deeptracy_1      |     return self.run(*args, **kwargs)
deeptracy_1      |   File "/usr/local/lib/python3.6/site-packages/deeptracy/tasks/scan_deps.py", line 41, in scan_deps
deeptracy_1      |     scan_deps = get_dependencies(scan.lang, scan.source_path)
deeptracy_1      |   File "/usr/local/lib/python3.6/site-packages/deeptracy/tasks/scan_deps.py", line 88, in get_dependencies
deeptracy_1      |     return get_dependencies_for_python(sources, mounted_vol, docker_volumes)
deeptracy_1      |   File "/usr/local/lib/python3.6/site-packages/deeptracy/tasks/scan_deps.py", line 239, in get_dependencies_for_python
deeptracy_1      |     version_part = pattern.split(parts[1])[1]
deeptracy_1      | IndexError: list index out of range
```

I don't know what's going on. Could you help me???
Thanks!

**Comment by iknite** [comment]
Just a quick check, it's `54ef977d835c48459ba85c2e9e82931f` given by your deeptracy instance, right?

**Comment by angelbarrera92** [comment]
Hi @iknite The `54ef....1f` id was recovered from the response of the first curl command. 

Thanks!

**Comment by Sergiodfdez** [comment]
Hello Angel,

When you create a project, with the command:

 `curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"repo":"https://github.com/BBVA/deeptracy-api.git","name":"deeptracy-api-test"}' \
  http://localhost:80/api/1/project/`

 get a response like this: 

`{
  "authType": "PUBLIC",
  "hookData": "",
  "hookType": "NONE",
  "id": "10f81ceb72e9499a8293c58ebc9a43c6",
  "name": "deeptracy-api-test",
  "repo": "https://github.com/BBVA/deeptracy-api.git",
  "scans": 0
}`

with the param `"id": "10f81ceb72e9499a8293c58ebc9a43c6"`, **in the second request you must use** this id:

`curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"project_id":"10f81ceb72e9499a8293c58ebc9a43c6","lang":"python"}' \
  http://localhost:80/api/1/scan/`

**this works**, becouse I receive the next response:

`{
  "branch": "master",
  "created": "Mon, 04 Jun 2018 08:35:07 GMT",
  "id": "ffd356c90650469ba96bcd2647d284a0",
  "lang": "python",
  "project_id": "10f81ceb72e9499a8293c58ebc9a43c6",
  "state": "PENDING",
  "total_packages": 0,
  "total_vulnerabilities": 0
}`

**Comment by angelbarrera92** [comment]
Hi mate. 

You're right. But when you see the upcomings log messages you will see the error i had posted yesterday. 

The error seems to be on some methods that has gone away from the pip package.

**Comment by nilp0inter** [comment]
I am closing this ticket now because we had a complete rewrite of the project.
Please open it again if you consider opportune after testing the new version.
